# Generated by Django 5.0 on 2023-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='images')),
                ('corredor', models.CharField(max_length=255)),
            ],
        ),
    ]
