# Generated by Django 5.0 on 2023-12-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corredor'),
        ),
    ]
