# Generated by Django 5.0 on 2023-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_corredor_alter_produto_corredor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='anuncios')),
                ('tempo', models.IntegerField()),
                ('expira', models.DateTimeField()),
            ],
        ),
    ]
