# Generated by Django 5.0 on 2023-12-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_anuncio_imagem_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='expira',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tempo',
            field=models.IntegerField(default=5),
        ),
    ]
